/* Generated by Yosys 0.59+0 (git sha1 529886f7fb8f0dd6339bca470a01db5e289755b5, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module ripple_adder(a, b, s, cout);
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  output [1:0] s;
  wire [1:0] s;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire \U1.W1 ;
  wire \U2.s ;
  XOR2_X1 _04_ (
    .A(a[0]),
    .B(b[0]),
    .Z(\U1.W1 )
  );
  NAND2_X1 _05_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(_03_)
  );
  XOR2_X1 _06_ (
    .A(a[1]),
    .B(b[1]),
    .Z(_00_)
  );
  NAND3_X1 _07_ (
    .A1(a[0]),
    .A2(b[0]),
    .A3(_00_),
    .ZN(_01_)
  );
  NAND2_X1 _08_ (
    .A1(_03_),
    .A2(_01_),
    .ZN(cout)
  );
  NAND2_X1 _09_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(_02_)
  );
  XNOR2_X1 _10_ (
    .A(_02_),
    .B(_00_),
    .ZN(\U2.s )
  );
  assign s = { \U2.s , \U1.W1  };
endmodule
